spring:
  redis:
    host: 192.168.100.100
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
